apiVersion: v1
kind: Secret
metadata:
  name: app-crud-secret
type: Opaque
data:
  DB_PASS: MTIyMzM0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-crud-config
data:
  DB_USER: puser
  DB_HOST: 0.0.0.0
  DB_NAME: crud