apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-crud-deployment
  labels:
    name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: app-crud
        image: franticjeremi/app-crud:v3
        ports:
          - name: web
            containerPort: 8000
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: app-crud-secret
                key: DB_PASS
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-crud-config
                key: DB_USER
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-crud-config
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-crud-config
                key: DB_NAME